/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, Car, Transport } from "@prisma/client";

export class CarServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CarFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CarFindManyArgs>
  ): Promise<number> {
    return this.prisma.car.count(args);
  }

  async findMany<T extends Prisma.CarFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CarFindManyArgs>
  ): Promise<Car[]> {
    return this.prisma.car.findMany(args);
  }
  async findOne<T extends Prisma.CarFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CarFindUniqueArgs>
  ): Promise<Car | null> {
    return this.prisma.car.findUnique(args);
  }
  async create<T extends Prisma.CarCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CarCreateArgs>
  ): Promise<Car> {
    return this.prisma.car.create<T>(args);
  }
  async update<T extends Prisma.CarUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CarUpdateArgs>
  ): Promise<Car> {
    return this.prisma.car.update<T>(args);
  }
  async delete<T extends Prisma.CarDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CarDeleteArgs>
  ): Promise<Car> {
    return this.prisma.car.delete(args);
  }

  async findTransports(
    parentId: string,
    args: Prisma.TransportFindManyArgs
  ): Promise<Transport[]> {
    return this.prisma.car
      .findUnique({
        where: { id: parentId },
      })
      .transports(args);
  }
}
