/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CarWhereInput } from "./CarWhereInput";
import { Type } from "class-transformer";
import { CarOrderByInput } from "./CarOrderByInput";

@ArgsType()
class CarFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => CarWhereInput,
  })
  @Field(() => CarWhereInput, { nullable: true })
  @Type(() => CarWhereInput)
  where?: CarWhereInput;

  @ApiProperty({
    required: false,
    type: CarOrderByInput,
  })
  @Field(() => CarOrderByInput, { nullable: true })
  @Type(() => CarOrderByInput)
  orderBy?: CarOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { CarFindManyArgs };
