/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateTransportArgs } from "./CreateTransportArgs";
import { UpdateTransportArgs } from "./UpdateTransportArgs";
import { DeleteTransportArgs } from "./DeleteTransportArgs";
import { TransportFindManyArgs } from "./TransportFindManyArgs";
import { TransportFindUniqueArgs } from "./TransportFindUniqueArgs";
import { Transport } from "./Transport";
import { CarFindManyArgs } from "../../car/base/CarFindManyArgs";
import { Car } from "../../car/base/Car";
import { TransportService } from "../transport.service";

@graphql.Resolver(() => Transport)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TransportResolverBase {
  constructor(
    protected readonly service: TransportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "read",
    possession: "any",
  })
  async _transportsMeta(
    @graphql.Args() args: TransportFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Transport])
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "read",
    possession: "any",
  })
  async transports(
    @graphql.Args() args: TransportFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Transport[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Transport",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Transport, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "read",
    possession: "own",
  })
  async transport(
    @graphql.Args() args: TransportFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Transport | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Transport",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Transport)
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "create",
    possession: "any",
  })
  async createTransport(
    @graphql.Args() args: CreateTransportArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Transport> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Transport",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Transport"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Transport)
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "update",
    possession: "any",
  })
  async updateTransport(
    @graphql.Args() args: UpdateTransportArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Transport | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Transport",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Transport"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Transport)
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "delete",
    possession: "any",
  })
  async deleteTransport(
    @graphql.Args() args: DeleteTransportArgs
  ): Promise<Transport | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Car])
  @nestAccessControl.UseRoles({
    resource: "Transport",
    action: "read",
    possession: "any",
  })
  async carId(
    @graphql.Parent() parent: Transport,
    @graphql.Args() args: CarFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Car[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Car",
    });
    const results = await this.service.findCarId(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
