/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { TransportWhereUniqueInput } from "./TransportWhereUniqueInput";
import { TransportUpdateInput } from "./TransportUpdateInput";

@ArgsType()
class UpdateTransportArgs {
  @Field(() => TransportWhereUniqueInput, { nullable: false })
  where!: TransportWhereUniqueInput;
  @Field(() => TransportUpdateInput, { nullable: false })
  data!: TransportUpdateInput;
}

export { UpdateTransportArgs };
